# coding=utf-8
"""Contain all the states of the telegram bot wishlist-shop.."""
(START, SELECTING_LANGUAGE, MAIN_MENU, SELECTING_IMPRESSIONS_CATEGORY,
 SELECTING_IMPRESSION, SELECTING_RECEIVING_METHOD, WAITING_CUSTOMER_EMAIL,
 ACQUAINTED_PRIVACY_POLICY, WAITING_CUSTOMER_FULLNAME, WAITING_CUSTOMER_PHONE,
 WAITING_CUSTOMER_CONFIRMATION, WAITING_PAYMENT_SCREENSHOT, DIALOGUE_END,
 SELECTING_DELIVERY_METHOD, WAITING_RECIPIENT_NAME,
 WAITING_RECIPIENT_CONTACT, WAITING_RECIPIENT_CONFIRMATION,
 CONFIRMING_SELF_DELIVERY, WAITING_CERTIFICATE_ID, WRONG_CERTIFICATE_MENU,
 SELECTING_QUESTION) = range(1, 22)
